# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - wget https://d2hvyiie56hcat.cloudfront.net/linux/amd64/installer/rpm/latest/aws-signer-notation-cli_amd64.rpm
      - sudo rpm -U aws-signer-notation-cli_amd64.rpm
      - notation plugin ls
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - VERSION="1.0.0"
      - curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
      - mkdir -p oras-install/
      - tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
      - sudo mv oras-install/oras /usr/local/bin/
      - curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      - curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
  post_build:
    commands:
      - echo Pushing the Docker images....
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - grype $REPOSITORY_URI:$IMAGE_TAG -o json > cve.json
      - syft $REPOSITORY_URI:$IMAGE_TAG -o spdx-json > sbom.spdx.json
      - oras attach --artifact-type cve/example $REPOSITORY_URI:$IMAGE_TAG cve.json:application/json
      - oras attach --artifact-type sbom/example $REPOSITORY_URI:$IMAGE_TAG sbom.spdx.json:application/json
      - CVEDIGEST=`oras discover -o json $REPOSITORY_URI:$IMAGE_TAG | jq -r '.manifests[0].digest'`
      - SBOMDIGEST=`oras discover -o json $REPOSITORY_URI:$IMAGE_TAG | jq -r '.manifests[1].digest'`
      - notation sign $REPOSITORY_URI:$IMAGE_TAG --plugin "com.amazonaws.signer.notation.plugin" --id "$SIGNER_PROFILE_ARN"
      - notation sign $REPOSITORY_URI@$CVEDIGEST --plugin "com.amazonaws.signer.notation.plugin" --id "$SIGNER_PROFILE_ARN"
      - notation sign $REPOSITORY_URI@$SBOMDIGEST --plugin "com.amazonaws.signer.notation.plugin" --id "$SIGNER_PROFILE_ARN"
